name: 'Install Dependencies'
description: 'Install project dependencies'

runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
