name: 'Authenticate NPM'
description: 'Creates .npmrc with token'

runs:
  using: composite
  steps:
    - name: Setup .npmrc
      shell: bash
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> "$HOME/.npmrc"
