name: 'Authenticate NPM'
description: 'Creates .npmrc with token'

runs:
  using: composite
  steps:
    - name: Setup .npmrc
      shell: bash
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> "$HOME/.npmrc"
