name: 'Authenticate NPM'
description: 'Creates .npmrc with token'

on:
  workflow_call:
    inputs:
      token:
        required: true
        type: string

runs:
  using: composite
  steps:
    - name: Setup .npmrc
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.token }}
      run: |
        echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> "$HOME/.npmrc"
