name: 'Authenticate NPM'
description: 'Creates .npmrc with token'

inputs:
  npmToken:
    required: true
    description: 'NPM token for authorizing npmrc. Used for private packages and releasing'

runs:
  using: composite
  steps:
    - name: Setup .npmrc
      shell: bash
      env:
        NPM_TOKEN: ${{ inputs.npmToken }}
      run: |
        touch .npmrc
        echo //registry.npmjs.org/:_authToken=$NPM_TOKEN >> .npmrc
