name: 'Setup Git'
description: 'Sets up Git'

runs:
  using: composite
  steps:
    - name: Setup Git User
      shell: bash
      run: |
        git config --global user.email "hi@ondrejlangr.cz"
        git config --global user.name "Ondřej Langr"
