name: 'Publish Packages Unstable'
description: 'Does unstable publish of packages'

runs:
  using: composite
  steps:
    - name: Version Packages - Unstable
      shell: bash
      run: pnpm run version:prerelease

    - name: Publish packages - Unstable
      shell: bash
      run: pnpm run release:prerelease
